slug: "sendspin"
name: "Sendspin"
description: "Sendspin client for local playback"
version: "0.7"
init: false
audio: true
realtime: true
host_network: true

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - addon_config:rw

startup: services

schema:
  static_delay_ms: str?
  name: str?
  id: str?
  url: str?
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?